### ISSUE TITLE
RFE:  MAC Binary needs plugins required to run oc compliance bind

### ISSUE THREAD

**Issue by npoyant** [openshift/oc-compliance#1]
currently not functioning with the mac based binary

$ oc compliance bind --name periodic-8 --settings periodic-setting profile/rhcos4-e8 profile/ocp4-e8
Error: unknown command "compliance" for "oc"
Run 'oc --help' for usage.

$ oc compliance bind
Error: unknown command "compliance" for "oc"
Run 'oc --help' for usage.

$ oc version
Client Version: openshift-clients-4.6.0-202006250705.p0-156-geadaf8954
Server Version: 4.6.0-0.nightly-2020-10-01-041253
Kubernetes Version: v1.19.0+beb741b

**Comment by JAORMX** [comment]
Where did you install the `oc-compliance` binary? That needs to be in the same directory as the `oc` binary so it can be autodiscovered.

**Comment by npoyant** [comment]
/usr/local/bin

**Comment by npoyant** [comment]
sorry if this wasn't clear.  The binary that was provided during the hack event worked.  I just created this issue so that it was documented on you guys end so it could be pushed to the official locations at the appropriate time.  If you want to close this issue out here that's fine.
